export const CardQuestions = [
  "What programming language is known for its use in web development?",
  "In design, what does UI stand for?",
  "Which of the following is a version control system?",
  "What does HTML stand for?",
  "In UX design, what does 'wireframing' refer to?",
  "Which CSS property is used for changing the text color of an element?",
  "What is the purpose of the 'alt' attribute in HTML?",
  "Which of the following is not a JavaScript data type?",
  "What does API stand for?",
  "What is the box model in CSS?",
  "In web development, what does the acronym AJAX stand for?",
  "Which of the following is a relational database management system?",
  "What is the primary function of the 'for' loop in programming?",
  "What is the role of a 'cookie' in web development?",
  "In responsive web design, what does 'media query' refer to?",
  "What is the purpose of the 'border-radius' property in CSS?",
  "Which of the following is a valid color representation in CSS?",
  "What does the 'src' attribute in an HTML 'img' tag specify?",
  "What is the purpose of the 'localStorage' object in JavaScript?",
  "Which tag is used for creating an unordered list in HTML?",
  "What is the role of a 'proxy server' in computer networks?",
  "In object-oriented programming, what is encapsulation?",
  "What is the difference between 'let' and 'const' in JavaScript?",
  "What is the purpose of the 'head' element in an HTML document?",
  "Which of the following is a commonly used HTTP status code for 'OK'?",
  "What is the purpose of the 'box-sizing' property in CSS?",
  "In programming, what is a 'callback function'?",
  "What does the 'typeof' operator do in JavaScript?",
  "What is the purpose of the 'target' attribute in an HTML 'a' tag?",
  "Which method is used for adding a new element to the end of an array in JavaScript?",
  "What does the 'float' property in CSS determine?",
  "In web development, what does 'SEO' stand for?",
  "What is the primary purpose of the 'form' element in HTML?",
  "Which of the following is a valid method for styling in React?",
  "What does the 'async' keyword do in JavaScript?",
  "What is the significance of the 'role' attribute in HTML?",
  "What is the purpose of the 'fetch' function in JavaScript?",
  "Which of the following is a commonly used HTTP method for retrieving data?",
  "In the context of databases, what is normalization?",
  "What is the purpose of the 'transition' property in CSS?",
  "Which CSS selector is used to select all elements with a specific class?",
  "In the context of color theory, what is complementary color?",
  "What is the significance of the 'aria-label' attribute in HTML?",
  "Which of the following is a commonly used HTTP status code for 'Not Found'?",
  "What is the purpose of the 'onClick' attribute in React?",
  "What does the acronym CRUD stand for in database operations?",
  "In JavaScript, what is the role of the 'setTimeout' function?",
];
